### ISSUE TITLE
Publish to packist

### ISSUE THREAD

**Issue by jg-development** [gwharton/autocustomergroup#6]
Hi,
is it possible to publish this to packagist?

**Comment by gwharton** [comment]
I've never done it before. As long as its not too complicated, I dont see why not. I'll take a look later today if thats ok.

**Comment by jg-development** [comment]
its easy ...
create an account
connect account to github
submit your repo
packagist will include it automatically by reading the composer.json

**Comment by gwharton** [comment]
Yes, looks like my vendor name is taken, so a little shuffling required. Standby.

**Comment by gwharton** [comment]
ok, thats now updated and on packagist. composer require gwharton/autocustomergroup

I've just bumped the version on github and it has reflected new version on packagist, so I guess thats all set.

**Comment by gwharton** [comment]
Let me know if you have any issues. All contributions and comments welcome. I'll close this issue now.

**Comment by jg-development** [comment]
thx ... seems to work
