### ISSUE TITLE
problem with using your module

### ISSUE THREAD

**Issue by mansato** [gwharton/autocustomergroup#8]
hello,

I have a problem with using your module.

module disabled:
if i have a user in the professional group who orders in uk, the vat is not charged. if it is in the general group the vat and well invoiced. 

module activated:
I put for -135 £ order in uk use group general
+ £ 135 order in uk use group profressional

I have placed several orders with the module activated and in all cases I have the VAT which and invoiced to the person while the module changes the group.

can you help me? thank you.

**Comment by gwharton** [comment]
Can you confirm you are using the latest version of the module. There have been some changes recently. The module outputs some debug/information to the var/log/system.log and var/log/debug.log every time the checkout requests totals, and also when the order is placed. It should show when it changes the group.

Are your orders being successfully placed with the correct group, if so, you need to make sure your tax rules are setup correctly. So for the tax rule for UK VAT, link that to customer group general, and do not link any tax rule to group professional. That way, one group will be charged, and the other won't.

First thing to determin if the right group is set for the order. If so, look at tax rules.

Heres an example of my setup for New Zealand.

### Customer Groups
![chrome_nSphv7G65I](https://user-images.githubusercontent.com/30697781/127685582-4bf9139c-9215-42eb-994b-f23b2fd72f6c.png)

### New Zealand Settings
![chrome_bJFyn6JXHR](https://user-images.githubusercontent.com/30697781/127686379-e8362ab7-7cf0-41a4-aaae-44590b55c828.png)

### Tax Rates
![chrome_osgR0b3x3o](https://user-images.githubusercontent.com/30697781/127686008-ef8a1780-5b82-46a9-988a-7be484ac18ce.png)

### Tax Rules
![chrome_RUuNlCgQqg](https://user-images.githubusercontent.com/30697781/127686074-9f177945-1124-4034-a28b-737bde4266f3.png)

Customer Group -> Customer Tax Class -> Tax Rule -> Tax Rate

I hope this helps. Let me know how you get on.

**Comment by gwharton** [comment]
Actually, I may have slightly misunderstood your question. I havent done much testing with customer accounts. Only guest orders. Let me run some tests with customer accounts and I'll get back to you.

**Comment by gwharton** [comment]
OK, i've found the issue in the code. Im working up a fix today so check in later for an update.

**Comment by gwharton** [comment]
Please try the latest version 0.6.0

There was an error with processing group changes with existing customer accounts.

Please let me know how you get on.

https://github.com/gwharton/autocustomergroup/releases/tag/v0.6.0

**Comment by mansato** [comment]
Hello,

I installed the update,  have another problem.

Order With your module si disable :
![image](https://user-images.githubusercontent.com/16746311/127832797-6779730f-f7db-4eb2-89d9-824ab30b9c58.png)

Same order with your module is enable:
![image](https://user-images.githubusercontent.com/16746311/127832964-fb4c7b13-d378-4445-8140-bad6d345c479.png)

the VAT is 0 but the price of the product remains in including tax.

Thanks.

**Comment by gwharton** [comment]
Give me a day or so to run some more tests. Thanks for your patience.

**Comment by gwharton** [comment]
Can you confirm whether you have Catalog prices set to include or exclude tax

**Comment by gwharton** [comment]
I need to understand how your system is setup, so can you please let me know what all the settings are set to on Config->Sales->Tax

**Comment by mansato** [comment]
hi,

I updated the module to version 0.6.1 and when i add new tax rule i have : 

1 exception(s):
Exception #0 (Magento\Framework\Exception\NoSuchEntityException): No such entity with taxRuleId =

**Comment by gwharton** [comment]
OK, try v0.6.2 just released. It should fix that issue.

https://github.com/gwharton/autocustomergroup/releases/tag/v0.6.2

**Comment by mansato** [comment]
ok, now it works, but I have another problem it is possible that it comes from my configuration.

notice: Undifined index: EU-UK-20.00% in /srv/easypara-web/www_root/app/code/Gw/AutoCustomerGroup/Model/Calculation/TaxRuleExtractor.php on line 50

"$outputRates = $appliedTaxes[$code]->getRates();"

**Comment by gwharton** [comment]
Let me take a look at that. be back shortly.

**Comment by gwharton** [comment]
OK, that was a specific failure case when "Tax included in Price" is set. Please try version 0.6.3

https://github.com/gwharton/autocustomergroup/releases/tag/v0.6.3

**Comment by gwharton** [comment]
Just be careful of having "Catalog prices include tax" set to "Include Tax". I'm pretty sure that isnt working properly as I just did a test with magento 2.4.3 fresh install and it doesn't work how it is expected to work.

**2.4.3 Setting - Tax included in Catalog Price**

Tax rule 20% for UK
Product with Catalog Price £120
Checkout should show exVAT price £100 and incVAT price £120
Checkout actually shows exVAT price £120 and incVAT price £144

**2.4.3 Setting - Tax not included in Catalog Price**

Tax rule 20% for UK
Product with Catalog Price £100
Checkout correctly shows exVAT price £100 and incVAT price £120

I think this is what you were seeing earlier in this comment https://github.com/gwharton/autocustomergroup/issues/8#issuecomment-890853342

I'm making some enquiries with core team on Slack regarding this.

**Comment by mansato** [comment]
I did another test it's all good on my side thank you.

**Comment by gwharton** [comment]
Brilliant. Let me know if you have any more issues.
